export default [
    {
        id:1,
        name:'programming',
        icon:'/coding.jpg',
        prompt:''
    },
    {
        id:2,
        name:'Health',
        icon:'/health.jpg',
        promp:''
    },
    {
        id:3,
        name:'creative',
        icon:'/create.jpg',
        promp:''
    },
]